name: quantum_ml_311
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.11
  - numpy>=1.24.0
  - scipy>=1.10.0
  - matplotlib>=3.7.0
  - pandas>=2.0.0
  - scikit-learn>=1.3.0
  - pytorch
  - torchvision
  - torchaudio
  - tensorflow
  - numba>=0.58.0
  - joblib>=1.3.0
  - plotly>=5.17.0
  - seaborn>=0.12.0
  - bokeh>=3.2.0
  - pip
  - pip:
    - psutil>=5.9.0
    - cirq>=1.6.1
    - qiskit>=0.45.0
    - pennylane>=0.32.0
    - tensorflow-quantum>=0.7.3
    - qiskit-machine-learning>=0.7.0
    - pennylane-lightning>=0.32.0
    - openfermion>=1.6.0
    - stable-baselines3>=2.0.0
    - optuna>=3.4.0
    - transformers>=4.35.0
    - cvxpy>=1.4.0
    - ortools>=9.8.0
    - flask>=2.3.0
    - requests>=2.31.0
    - pydantic>=2.4.0
    - pytest>=7.4.0
    - black>=23.9.0
    - memory-profiler>=0.61.0
    - py-cpuinfo>=9.0.0
    - loguru>=0.7.0
    - pennylane-qiskit>=0.32.0
    - pennylane-cirq>=0.32.0
    - qiskit-algorithms>=0.2.0
    - networkx>=3.2.0
    - python-constraint>=1.4.0
    - sympy>=1.12.0